BEGIN;

-- 1) ROLES (no login)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fin_ro') THEN
    CREATE ROLE fin_ro NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fin_rw') THEN
    CREATE ROLE fin_rw NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fin_admin') THEN
    CREATE ROLE fin_admin NOLOGIN;
  END IF;
END $$;

-- 2) Jerarquía (admin > rw > ro)
GRANT fin_ro TO fin_rw;
GRANT fin_rw TO fin_admin;

-- 3) Permisos sobre schema y objetos existentes
GRANT USAGE ON SCHEMA fin TO fin_ro, fin_rw, fin_admin;

GRANT SELECT ON ALL TABLES IN SCHEMA fin TO fin_ro;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA fin TO fin_rw;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA fin TO fin_admin;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA fin TO fin_rw, fin_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA fin TO fin_ro;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA fin TO fin_rw, fin_admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA fin TO fin_ro;

-- 4) Defaults (para todo lo que crees después)
ALTER DEFAULT PRIVILEGES IN SCHEMA fin GRANT SELECT ON TABLES TO fin_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA fin GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fin_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA fin GRANT ALL PRIVILEGES ON TABLES TO fin_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA fin GRANT USAGE, SELECT ON SEQUENCES TO fin_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA fin GRANT USAGE, SELECT ON SEQUENCES TO fin_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA fin GRANT USAGE, SELECT ON SEQUENCES TO fin_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA fin GRANT EXECUTE ON FUNCTIONS TO fin_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA fin GRANT EXECUTE ON FUNCTIONS TO fin_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA fin GRANT EXECUTE ON FUNCTIONS TO fin_admin;

-- 5) Asignar rol a tu usuario app
DO $$
DECLARE
  app_user text := 'evalua_user'; -- <-- CAMBIA AQUÍ
BEGIN
  EXECUTE format('GRANT fin_rw TO %I', app_user);
END $$;

COMMIT;